### PR TITLE
[Packing] Client fonts using file-loader.

### PR DESCRIPTION
**Pull request by philliphoff**
The Client is currently not able to find its custom fonts because WebPack is placing them relative to the root of the web application.  Using a relative path requires a custom loader (e.g. `file-loader`), which seems to resolve the problem.

(Interestingly, this same trick doesn't seem to work for the HUD, perhaps due to the way it's injected into the host page.)

### CODE REVIEW

**Comment by avanderhoorn** [comment]
Did this end up getting rid of all the 404s?

**Comment by philliphoff** [comment]
Yes, no 404s; the requests for the fonts now return 200s.

**Comment by philliphoff** [comment]
Feel free to give it a try before merging to make sure you're seeing what you expect.

**Comment by avanderhoorn** [comment]
Once the conflicts here are sorted this can come in

**Pull request merged**
