### PR TITLE
Display logging offsets, if available.

### PR DESCRIPTION
**Pull request by philliphoff**
If logging messages are published with corresponding offsets, displays the offsets on the logging tab.

### CODE REVIEW

**Comment by avanderhoorn** [comment]
Looks good. Only thing is that the offset will likely need to be computed from the timestamp. My memory of the discussion we had was that all the messages would be coming in with a normalized timestamp but we would still need to calculate the offset locally.

**Comment by philliphoff** [comment]
> Looks good. Only thing is that the offset will likely need to be computed from the timestamp. My memory of the discussion we had was that all the messages would be coming in with a normalized timestamp but we would still need to calculate the offset locally.

Based on @mike-kaufman's summary email, the decision was for the offset to be included as message payload and belonging to an offset-specific message type (where the offset is relative to the timestamp that represents the beginning of the associated context).  The fact that that context timestamp will (eventually) be generated by a clock sync'd with others (making offsets more comparable across contexts and across agents), is a separate question.

**Comment by mike-kaufman** [comment]
Is this ready to go in?  Been sitting here for a while...

**Comment by philliphoff** [comment]
@mike-kaufman: There's still ongoing discussion about what message type the offset property should belong to, as well as a couple of other things, so this PR is shelved for now.

**Comment by avanderhoorn** [comment]
Closing for the time being.

**Pull request closed without merging**
